recipe_root: /Users/priyatam/Dev/github/facjure/poems/site
content: /Users/priyatam/Dev/github/facjure/poems/poems

first_page: blog
default_template: blog.mustache

title: 5000 Poems by Ata Moharreri

